### PR TITLE
fix for negative values reported by joularjx

### PR DESCRIPTION
**Pull request by kifetew**
Fixes that resolve problems with negative values reported by joularjx.

### CODE REVIEW

**Comment by adelnoureddine** [comment]
Is it possible to revert the modifications you did to pom.xml, powemetrics and RAPL file?

**Comment by kifetew** [comment]
> Is it possible to revert the modifications you did to pom.xml, powemetrics and RAPL file?

sure, I can send another PR removing those modifications. Keep in mind that the change in RAPL is needed to avoid multiple initialization, while the change in powermetricsmacos is to enable the energy reading in mac

**Comment by adelnoureddine** [comment]
> > Is it possible to revert the modifications you did to pom.xml, powemetrics and RAPL file?
> 
> sure, I can send another PR removing those modifications. Keep in mind that the change in RAPL is needed to avoid multiple initialization, while the change in powermetricsmacos is to enable the energy reading in mac

Thanks a lot @kifetew.

For RAPL, we can have another PR.

For Intel Mac, we have an ongoing PR #55  which have a nice approach to support reading powermetrics with different output. You can check their solution if it works on your mac, and don't hesitate to contribute in the discussion and code there too.

**Comment by kifetew** [comment]
> > > Is it possible to revert the modifications you did to pom.xml, powemetrics and RAPL file?
> > 
> > 
> > sure, I can send another PR removing those modifications. Keep in mind that the change in RAPL is needed to avoid multiple initialization, while the change in powermetricsmacos is to enable the energy reading in mac
> 
> Thanks a lot @kifetew.
> 
> For RAPL, we can have another PR.
> 
> For Intel Mac, we have an ongoing PR #55 which has a nice approach to support reading powermetrics with different output. You can check their solution if it works on your mac, and don't hesitate to contribute in the discussion and code there too.

I've created another PR removing the changes you mentioned. For RAPL, the fix is only a matter of changing List to Set. I'll check the mac fix in PR 55.

**Comment by adelnoureddine** [comment]
Thanks. I'll close this PR and check the other one.

**Pull request closed without merging**
